// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikfnezrcppouhjgpnbtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZm5lenJjcHBvdWhqZ3BuYnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTQzMTEsImV4cCI6MjA1OTY3MDMxMX0.k_IVcr_6DrlOKrrdwpkxVVbs1f59ZXVTAaPip3ma-7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);